name: 0815-0178notebook_with1NNs-optuna

version_fe: 1

sampling_ratio: 0.01
rank_avg: true
dnn_binning: false

dnn_predictions:
  # - name: 0810-swinv2_small-transV2-lr1e-3-target_decay001-bs32_8-drop01-ep80
  #   dir: /workspace/logs/train/runs/0810-swinv2_small-transV2-lr1e-3-target_decay001-bs32_8-drop01-ep80/train_predictions
  # - name: 0808-tip_finetune-efficientnet_b2_l3d384-tabV3-transV8-bs_64_8-neg50-ep400-lr1e-3-target_decay001-warmup10-transV2
  #   dir: /workspace/logs/train/runs/0808-tip_finetune-efficientnet_b2_l3d384-tabV3-transV8-bs_64_8-neg50-ep400-lr1e-3-target_decay001-warmup10-transV2/train_predictions
  # - name: 0811-convnextv2_tiny-meta_target03-transV2-lr1e-3-target_decay001-bs128_2-ep80
  #   dir: /workspace/logs/train/runs/0811-convnextv2_tiny-meta_target03-transV2-lr1e-3-target_decay001-bs128_2-ep80/train_predictions
  # - name: 0808-tip_frozen-convnextv2_nano_l3d384-tabV3-transV8-lr5e-4-warmup50-bs_64_8-neg50-ep400-lr1e-3-transV2-ep20
  #   dir: /workspace/logs/train/runs/0808-tip_frozen-convnextv2_nano_l3d384-tabV3-transV8-lr5e-4-warmup50-bs_64_8-neg50-ep400-lr1e-3-transV2-ep20/train_predictions
  # - name: 0808-tip_finetune_onlyImage-efficientnet_b2_l3d384-tabV3-transV8-bs_64_8-neg50-ep400-lr1e-3-target_decay001-warmup10-transV2
  #   dir: /workspace/logs/train/runs/0808-tip_finetune_onlyImage-efficientnet_b2_l3d384-tabV3-transV8-bs_64_8-neg50-ep400-lr1e-3-target_decay001-warmup10-transV2/train_predictions
  - name: 0813-convnextv2_tiny-meta_target03-transV2-lr1e-3-target_decay001-bs128_2-ep150-neg5
    dir: /workspace/logs/train/runs/0813-convnextv2_tiny-meta_target03-transV2-lr1e-3-target_decay001-bs128_2-ep150-neg5/train_predictions
  # - name: 0815-efficientnet_b0-meta_target1-transV2-lr1e-4-warmup20-bs128_2-ep150-neg5
  #   dir: /workspace/logs/train/runs/0815-efficientnet_b0-meta_target1-transV2-lr1e-4-warmup20-bs128_2-ep150-neg5/train_predictions
  # - name: 0808-tip_finetune-efficientnet_b2_l3d384-tabV3-transV8-bs_64_8-neg50-ep400-lr1e-3-target_decay001-warmup20-transV2-ep100-neg5
  #   dir: /workspace/logs/train/runs/0808-tip_finetune-efficientnet_b2_l3d384-tabV3-transV8-bs_64_8-neg50-ep400-lr1e-3-target_decay001-warmup20-transV2-ep100-neg5/train_predictions
  # - name: 0813-efficientnet_b0-scratch-transV2-lr3e-3-warmup50-bs128_2-ep500-neg5
  #   dir: /workspace/logs/train/runs/0813-efficientnet_b0-scratch-transV2-lr3e-3-warmup50-bs128_2-ep500-neg5/train_predictions

  # - name: 
  #   dir: /workspace/logs/train/runs//train_predictions

use_logits: false

models:
  - type: lgb
    n_seed_averaging: 3
    params:
      objective: "binary"
      verbosity: -1
      n_iter: 200
      boosting_type: "gbdt"
      random_state: ${seed}
      learning_rate: 0.03
      lambda_l1: 0.0592494163746506
      lambda_l2: 0.11028237732557318
      max_depth: 4
      num_leaves: 34
      colsample_bytree: 0.6986221132007755
      colsample_bynode: 0.47548298499927616
      bagging_fraction: 0.9725139264006484
      bagging_freq: 1
      min_data_in_leaf: 62
      scale_pos_weight: 0.8013523678765682

  - type: cb
    n_seed_averaging: 3
    params:
      loss_function:    Logloss
      iterations:       200
      verbose:          False
      random_state:     ${seed}
      # max_depth:        7　入れ忘れ未調整
      learning_rate: 0.03
      max_depth: 5
      scale_pos_weight: 3.8316742165119746
      l2_leaf_reg: 0.220601026409132
      subsample: 0.5778763294094978
      min_data_in_leaf: 48

  - type: xgb
    n_seed_averaging: 3
    params:
      enable_categorical: True
      n_estimators: 200
      tree_method:        hist
      random_state:       ${seed}
      learning_rate: 0.03
      lambda: 0.972580651471495
      alpha: 0.059163035784056135
      max_depth: 4
      subsample: 0.9233771383110415
      colsample_bytree: 0.7000231467839317
      colsample_bylevel: 0.7060686791229422
      colsample_bynode: 0.5034739507546538
      scale_pos_weight: 3.2957928785662003
