defaults:
  - loss: ce

_target_: src.models.isic2024_module_mmcosine.ISIC2024LitModule

use_image: true
use_metadata: true

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 1e-3

optimize_config:
  mode: normal
  head_name: linear
  head_lr_coef: 0.1

scheduler:
  _target_: transformers.get_cosine_schedule_with_warmup
  _partial_: true
  num_warmup_steps: 5
  num_training_steps: ${trainer.max_epochs}

net:
  _target_: src.models.components.image_meta_model_mmcosine.ISICModel
  image_model:
    _target_: src.models.components.timm_model_origin.ISICModel
    model_name: tf_efficientnet_b0_ns
    num_classes: 2
    pretrained: true
  meta_model:
    _target_: src.models.components.meta_model.ISICModel
    num_inputs: 68
  scaling: 10
  num_classes: 2
  dropout: 0.5

# compile model for faster training with pytorch 2.0
compile: false

tta: false
preds_save_path: ${log_dir}/test_predictions/fold{data.fold}.pt