defaults:
  - loss: ce

_target_: src.models.isic2024_module_ce.ISIC2024LitModule

use_image: true
use_metadata: false

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.001
  weight_decay: 1e-3

optimize_config:
  mode: normal
  head_name: linear
  head_lr_coef: 0.1

scheduler:
  _target_: transformers.get_cosine_schedule_with_warmup
  _partial_: true
  num_warmup_steps: 5
  num_training_steps: ${trainer.max_epochs}

net:
  _target_: src.models.components.patient_set_timm_gat.ISICModel
  model_name: tf_efficientnet_b0_ns
  num_classes: 2
  pretrained: true
  batch_size: ${data.batch_size}
  n_data_per_patient: ${data.n_data_per_patient}

# compile model for faster training with pytorch 2.0
compile: false

tta: false
preds_save_path: ${log_dir}/test_predictions/fold${data.fold}.pt