# @package _global_

defaults:
  - _self_
  - data: isic2024
  - model: timm_model
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - experiment: null

task_name: "pred"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ???