name: 0731-fe1-eva02_s-im_en_b0-im_cn_t-lgb_fe1

dnn_predictions:
  - name: 0722-eva02_small-transV2-lr5e-5-bs256-drop02
    dir: /workspace/logs/train/runs/0722-eva02_small-transV2-lr5e-5-bs256-drop02/train_predictions
  - name: 0724-image_meta-efficientnet_b0-lr5e-4-bs512-bn
    dir: /workspace/logs/train/runs/0724-image_meta-efficientnet_b0-lr5e-4-bs512-bn/train_predictions
  - name: 0725-image_meta-convnextv2_tiny-lr5e-4-bs512-bn-inter_ce-metaPre10
    dir: /workspace/logs/train/runs/0725-image_meta-convnextv2_tiny-lr5e-4-bs512-bn-inter_ce-metaPre10/train_predictions
use_logits: false

lightgbm_configs:
  - name: 0731-lgb-fe1
    dir: /workspace/logs/lgb/runs/0731-lgb-fe1

version_fe: 1


lightgbm:
  params:
    objective: "binary"
    metric: "binary_logloss"
    boosting_type: "gbdt"
    verbosity: -1
    seed: ${seed}
    bagging_fraction: 0.5183783072886006
    bagging_freq: 1
    feature_fraction: 0.41600000000000004
    feature_pre_filter: False
    lambda_l1: 5.288290588274316e-08
    lambda_l2: 8.348806594782424
    min_child_samples: 10
    num_leaves: 2
    learning_rate: 0.005
  num_boost_round: 3000
  early_stopping: 100

catboost:
  params:
    objective: 'Logloss'
    random_state: ${seed}
    colsample_bylevel: 0.3
    learning_rate: 0.01
    max_depth: 8
    l2_leaf_reg: 5
    verbose: 1
    iterations: 3000
    early_stopping_rounds: 100
    metric_period: 20