name: 0809-logistic-lgb-cb-tip_en_b0-swin_b-eva02_s-im_en_b0-cn_t_mt-gbdt_note-gbdt_fe2

version_fe: null

dnn_predictions:
  - name: 0804-tip_finetune-bs_64_8
    dir: /workspace/logs/train/runs/0804-tip_finetune-bs_64_8/train_predictions
  - name: 0721-swinv2_base-transV2-lr5e-5-bs256-drop02
    dir: /workspace/logs/train/runs/0721-swinv2_base-transV2-lr5e-5-bs256-drop02/train_predictions
  - name: 0722-eva02_small-transV2-lr5e-5-bs256-drop02
    dir: /workspace/logs/train/runs/0722-eva02_small-transV2-lr5e-5-bs256-drop02/train_predictions
  - name: 0806-image_meta-efficientnet_b0-lr5e-4-bs512-bn
    dir: /workspace/logs/train/runs/0806-image_meta-efficientnet_b0-lr5e-4-bs512-bn/train_predictions
  - name: 0807-convnextv2_tiny-meta_target03-transV2-lr1e-3-target_decay001-bs128_2
    dir: /workspace/logs/train/runs/0807-convnextv2_tiny-meta_target03-transV2-lr1e-3-target_decay001-bs128_2/train_predictions
use_logits: false

gbdt_configs:
  - name: 0808-0178notebook
    dir: /workspace/logs/gbdt/runs/0808-0178notebook
  - name: 0809-fe2-lgb-cb-xgb
    dir: /workspace/logs/gbdt/runs/0809-fe2-lgb-cb-xgb


models:
  - type: logistic
    params:
      penalty: l2
      C: 1
      random_state: ${seed}
      max_iter: 100

  - type: lgb
    params:
      objective: "binary"
      verbosity: -1
      n_iter: 100
      boosting_type: "gbdt"
      random_state: ${seed}
      bagging_fraction: 1.0
      bagging_freq: 0
      feature_fraction: 0.4
      feature_pre_filter: False
      lambda_l1: 9.080573908495493e-06
      lambda_l2: 1.022151393545849e-05
      min_child_samples: 20
      num_leaves: 3
      learning_rate: 0.05

  - type: cb
    params:
      objective: 'Logloss'
      random_state: ${seed}
      verbose: False
      iterations: 100