name: 0714-optuna_best

params:
  objective: "binary"
  metric: "binary_logloss"
  boosting_type: "gbdt"
  verbosity: -1
  seed: ${seed}
  bagging_fraction: 0.5902709620094059
  bagging_freq: 6
  feature_fraction: 0.88
  feature_pre_filter: False
  lambda_l1: 0.45565678596274184
  lambda_l2: 6.175765148656141
  min_child_samples: 20
  num_leaves: 5

num_boost_round: 1000
early_stopping: 50