name: 0714-notebook_sample

params:
  objective: "binary"
  metric: "binary_logloss"
  boosting_type: "gbdt"
  verbosity: -1
  seed: ${seed}
  learning_rate: 0.01
  bagging_freq: 1
  pos_bagging_fraction: 0.75
  neg_bagging_fraction: 0.05
  feature_fraction: 0.8
  lambda_l1: 0.8
  lambda_l2: 0.8

num_boost_round: 1000
early_stopping: 50