name: 0720-optuna_best-convnextv2_base

dnn_predictions:
  - name: 0717-convnextv2_base-transV2-lr1e-4-bs256
    dir: /workspace/logs/train/runs/0717-convnextv2_base-transV2-lr1e-4-bs256/train_predictions

params:
  objective: "binary"
  metric: "binary_logloss"
  boosting_type: "gbdt"
  verbosity: -1
  seed: ${seed}
  bagging_fraction: 0.5902709620094059
  bagging_freq: 6
  feature_fraction: 0.88
  feature_pre_filter: False
  lambda_l1: 0.45565678596274184
  lambda_l2: 6.175765148656141
  min_child_samples: 20
  num_leaves: 5
  learning_rate: 0.005

num_boost_round: 1000
early_stopping: 50