name: 0721-optuna_best-convnextv2_base-efficientnet_b0

dnn_predictions:
  - name: 0717-convnextv2_base-transV2-lr1e-4-bs256
    dir: /workspace/logs/train/runs/0717-convnextv2_base-transV2-lr1e-4-bs256/train_predictions
  - name: 0721-efficientnet_b0-transV2-lr1e-4-bs256
    dir: /workspace/logs/train/runs/0721-efficientnet_b0-transV2-lr1e-4-bs256/train_predictions

params:
  objective: "binary"
  metric: "binary_logloss"
  boosting_type: "gbdt"
  verbosity: -1
  seed: ${seed}
  bagging_fraction: 0.6543541123089598
  bagging_freq: 7
  feature_fraction: 0.52
  feature_pre_filter: False
  lambda_l1: 2.0435647617542072e-05
  lambda_l2: 0.0001375806112635315
  min_child_samples: 20
  num_leaves: 5
  learning_rate: 0.005

num_boost_round: 1000
early_stopping: 50