name: 0723-convnextv2_base-efficientnet_b0-swinv2_base-eva02_small-image_meta

# add_noiseしてチューニング、訓練時にはadd_noiseしない

dnn_predictions:
  - name: 0717-convnextv2_base-transV2-lr1e-4-bs256
    dir: /workspace/logs/train/runs/0717-convnextv2_base-transV2-lr1e-4-bs256/train_predictions
  - name: 0721-efficientnet_b0-transV2-lr1e-4-bs256
    dir: /workspace/logs/train/runs/0721-efficientnet_b0-transV2-lr1e-4-bs256/train_predictions
  - name: 0721-swinv2_base-transV2-lr5e-5-bs256-drop02
    dir: /workspace/logs/train/runs/0721-swinv2_base-transV2-lr5e-5-bs256-drop02/train_predictions
  - name: 0722-eva02_small-transV2-lr5e-5-bs256-drop02
    dir: /workspace/logs/train/runs/0722-eva02_small-transV2-lr5e-5-bs256-drop02/train_predictions
  - name: 0722-image_meta-efficientnet_b0-lr5e-4-bs512
    dir: /workspace/logs/train/runs/0722-image_meta-efficientnet_b0-lr5e-4-bs512/train_predictions

params:
  objective: "binary"
  metric: "binary_logloss"
  boosting_type: "gbdt"
  verbosity: -1
  seed: ${seed}
  bagging_fraction: 0.5183783072886006
  bagging_freq: 1
  feature_fraction: 0.41600000000000004
  feature_pre_filter: False
  lambda_l1: 5.288290588274316e-08
  lambda_l2: 8.348806594782424
  min_child_samples: 10
  num_leaves: 2
  learning_rate: 0.005

num_boost_round: 3000
early_stopping: 50
